# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

spark.sql("USE CATALOG `hls_glucosphere`")
spark.sql("USE SCHEMA `cgm`")

# COMMAND ----------

# MAGIC %sql
# MAGIC select incident_type, has_incident, count(*) as freq
# MAGIC
# MAGIC from hls_glucosphere.cgm.pseudo_incident_7d_labeled_v20260105
# MAGIC group by 1, 2
# MAGIC order by freq

# COMMAND ----------

# MAGIC %sql
# MAGIC select device_model, firmware_version, avg(glucose_out_of_range)
# MAGIC from hls_glucosphere.cgm.gold_patient_device_readings
# MAGIC group by device_model, firmware_version
# MAGIC order by device_model asc

# COMMAND ----------

# MAGIC %sql
# MAGIC select time, firmware_version, avg(glucose)
# MAGIC from hls_glucosphere.cgm.gold_patient_device_readings
# MAGIC group by time, firmware_version
# MAGIC order by time asc

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT
# MAGIC   `time`,
# MAGIC   `firmware_version`,
# MAGIC   AVG(`glucose_out_of_range`) AS avg_glucose_out_of_range_pct
# MAGIC FROM
# MAGIC   `hls_glucosphere`.`cgm`.`gold_patient_device_readings`
# MAGIC WHERE
# MAGIC   `time` IS NOT NULL
# MAGIC   AND `firmware_version` IS NOT NULL
# MAGIC GROUP BY
# MAGIC   `time`,
# MAGIC   `firmware_version`
# MAGIC ORDER BY
# MAGIC   `time` ASC,
# MAGIC   `firmware_version` ASC

# COMMAND ----------

# MAGIC %sql
# MAGIC select time, device_model, avg(glucose_out_of_range)
# MAGIC from hls_glucosphere.cgm.gold_patient_device_readings
# MAGIC group by time, device_model
# MAGIC order by time asc

# COMMAND ----------

# MAGIC %sql
# MAGIC select time, firmware_version, avg(glucose_out_of_range)
# MAGIC from hls_glucosphere.cgm.gold_patient_device_readings
# MAGIC group by time, firmware_version
# MAGIC order by time asc

# COMMAND ----------

# MAGIC %sql
# MAGIC select time, firmware_version, avg(glucose_out_of_range), avg(glucose)
# MAGIC from hls_glucosphere.cgm.gold_patient_device_readings
# MAGIC group by time, firmware_version
# MAGIC order by time asc
